### PR TITLE
fix: sd-webui reporting 500 error using img2img

### LINKED ISSUE #104: Bug: 本地sd是否支持img2img
### Describe the bug

本地部署的sd,text2img成功，但是img2img一直失败，无报错信息,qq机器人调用报错500，接口信息如下：

### Steps to reproduce

本地部署

### Expected behavior

支持图生图模式

### Screenshots

image

### Relevant log output

_No response_

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version: 
全部最新版本

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaikoTan**
The Stable Diffusion Web UI changed their API recently, the prototype img2img API accepts data URLs and bare base64 encoded image both. But in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3511 they changed the function so that only data URLs accepted now (and didn't catch the exception).

This patch is trying to add an experimental data URL prefix for the base64 string, in order to match the changes on Stable Diffusion Web UI side.

Fixes #104

------

稳定的扩散网页用户界面最近改变了他们的API，原型img2img API接受数据URL和纯粹base64编码的图像。但是在 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3511 他们改变了函数，使得现在仅有数据URL被接受（而且没有捕获异常）。

这个补丁试图为base64字符串添加一个试验性的数据URL前缀，以匹配稳定的扩散网页用户界面方面的改动。

修复 #104

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -166,7 +166,7 @@ export function apply(ctx: Context, config: Config) {
         }
 
         Object.assign(parameters, {
-          image: image[1],
+          image,
```
Comment (shigma) [inline src/index.ts:169]: Is it no longer needed here? It would be better left to the `data` callback below.

File: src/utils.ts [hunk 2]
```diff
@@ -47,7 +47,7 @@ const MAX_OUTPUT_SIZE = 1048576
 const MAX_CONTENT_SIZE = 10485760
 const ALLOWED_TYPES = ['image/jpeg', 'image/png']
 
-export async function download(ctx: Context, url: string, headers = {}): Promise<[ArrayBuffer, string]> {
+export async function download(ctx: Context, url: string, headers = {}): Promise<[buffer: ArrayBuffer, base64: string, dataUrl: string]> {
```
Comment (shigma) [inline src/utils.ts:50]: This type is a bit complicated, it is recommended to return an interface `ImageData` instead.

**Review by shigma — CHANGES_REQUESTED** [review]

File: src/index.ts [hunk 3]
```diff
@@ -152,9 +152,10 @@ export function apply(ctx: Context, config: Config) {
         ucPreset: 2,
         qualityToggle: false,
       }
+      
+      let image: ImageData
```
Comment (shigma) [inline src/index.ts:156]: This can be grouped with above code for better SoC:

```ts
let imgUrl: string, image: ImageData
```

Comment (MaikoTan) [reply src/index.ts:156]: Well, I always declare them in separated lines even in the same scope. 🤣 
But-uh, I am willing to do the changes as you requested. 
Tout le plaisir est pour moi, monsieur ! 🎉

Comment (shigma) [reply src/index.ts:156]: You can also write them on two lines if you like:

```ts
let imgUrl: string
let image: ImageData
```

Comment (MaikoTan) [reply src/index.ts]: Ça devrait aller maintenant. C'est pas grave.

**Review by shigma — APPROVED** [review]
