### PR TITLE
fix: could not use `-r` in regular command invoke

### LINKED ISSUE #159: Bug: 使用-r参数自定义分辨率报错
### Describe the bug

在qq或沙盒里发送`nai -r 512x512 cat`，bot回复`选项 resolution 输入无效，Cannot read properties of null (reading 'authority')`。
不加-r参数bot回复正常。发送`nai -r landscape cat`bot回复正常。

### Steps to reproduce

在qq或沙盒里发送`nai -r 512x512 cat`

### Expected behavior

bot发送一张512x512大小的图

### Screenshots

QQ截图20230124101411

### Relevant log output

```shell
[W] i18n missing "Cannot read properties of null (reading 'authority')"
```

### Launcher

Koishi CLI (koishi start)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows 11
- Adapter: onebot
- Node version: 18.12.1
- Koishi version: 4.11.3
- koishi-plugin-novelai version: 1.16.0

### Additional context

已开启sqlite数据库插件

### PR DESCRIPTION
**Pull request by MaikoTan**
fix #159 

Also change a bit i18n typo.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -114,6 +113,14 @@ export function apply(ctx: Context, config: Config) {
     .action(async ({ session, options }, input) => {
       if (!input?.trim()) return session.execute('help novelai')
 
+      // Check if the user is allowed to use this command.
+      // This code is originally written in the `resolution` function,
+      // but currently `session.user` is not available in the type infering process.
+      // See: https://github.com/koishijs/novelai-bot/issues/159
+      if (options.resolution?.custom && restricted(session)) {
+        return session.text('.custom-resolution-unsupported')
+      }
```
Comment (MaikoTan) [inline src/index.ts:122]: Don't know why but `options.resolution` here is `any` rather than `Size`, is it bug or just my local configurations broke again?
