### PR TITLE
fix: hires fix broken on some webui backend

### LINKED ISSUE #158: Bug: 启用hiresFix后图片输出错误
### Describe the bug

本地部署的sd-webui启用hiresFix后图片输出错误，请参考Screenshots中的截图，Koish后台日志一切正常，只有聊天内容不方便展示。通过webui的控制台发现启用hiresFix后输出图像的速度没有太大变换（甚至感觉变快了），这不符合逻辑。

### Steps to reproduce

参数
启用hiresFix后会重现该现象，我不知道其它参数是否有影响，具体参数参考截图，可能的原因是启用hiresFix后超过了图片最大尺寸，但实际测试拉到足够的最大尺寸仍然会重现该现象。

### Expected behavior

无法启用hiresFix会导致图像质量偏低，希望能够给出解决方案。

### Screenshots

2_SR(PASZ{4ROQ4QW$VV9TH

### Relevant log output

_No response_

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version: 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaikoTan**
close #158

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -267,6 +267,11 @@ export function apply(ctx: Context, config: Config) {
             return { model, input: prompt, parameters: omit(parameters, ['prompt']) }
           }
           case 'sd-webui': {
+            // set default denoising strength to `0.75` for `hires fix` feature
+            // https://github.com/koishijs/novelai-bot/issues/158
+            if (options.hiresFix || config.hiresFix) {
+              parameters.strength ??= 0.75
```
Comment (shigma) [inline src/index.ts:273]: It looks wield to just set default strength when hiresFix is enabled. Can this be changed to "when backend is sd" or other behavior?

Comment (shigma) [reply src/index.ts:273]: Ohhhh I see. Then why not removing the `if` statement and just set the default value to 0.75?

Comment (MaikoTan) [reply src/index.ts:273]: Well, that makes sense too.

Comment (shigma) [reply src/index.ts]: I think it would be more reasonable to move the if out of the case, and set default value to 0.75 regardless of sd-webui. in case there are more backends to come.

Comment (MaikoTan) [reply src/index.ts]: But there are only sd-webui provides `hires fix` feature, for now at least.

Comment (shigma) [reply src/index.ts]: How about stable horde?

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

Comment (MaikoTan) [reply src/index.ts]: They don't have this feature currently.

Comment (MaikoTan) [reply src/index.ts]: You see, stable horde is a completely independent application compare to stable diffusion webui, so they have no any even relationship except using stable diffusion algorithms and models.

Comment (shigma) [reply src/index.ts]: That makes sense. Another concern I have is is this default of 0.75 what most people expect? Will it have a big impact on the resulting image?

Comment (MaikoTan) [reply src/index.ts]: I DON'T KNOW.

But 0.75 is the default value of sd-webui for generating images with `hires fix` enabled. So I wrote this specific value.

Comment (MaikoTan) [reply src/index.ts]: It is also possible for users to change the value by adding `--strength` parametres, so I don't think it is a big deal.

As for the `resulting image`, since you are using `hires fix`, it would not gerantee that you could use the same parametres to reproduce the same result with the same seed. If you're referring the content, the second part of `hires fix` would still feeds the same prompts to the diffusion model, so at least it would not show you a dinosaur while you are writing Bulbasaur.

Comment (shigma) [reply src/index.ts]: > 0.75 is the default value of sd-webui for generating images with hires fix enabled.

> So I think it would be more reasonable to move the if statement out of the case, and set default value to 0.75 regardless of sd-webui.

Other backends which do not support this feature also do not have this option on the first place.

Comment (MaikoTan) [reply src/index.ts]: Yep. So I think it is good for now.

Comment (shigma) [reply src/index.ts]: Ehhhh I mean moving the `if` outwards would be ok and furthermore be conducive to decoupling - the place you modified should only be related to request payloads, not default behavior of parameters.

Comment (MaikoTan) [reply src/index.ts]: But the others backends have their own default `strength` value which are not expectedly the same with `sd-webui`'s. The `strength` we are setting here just an in-case for txt2img api that has default `denoising_strength` set to 0 that causes error. Shouldn't we not to change the default behaviours for other backends?

Comment (shigma) [reply src/index.ts]: I believe you misunderstood. What do I mean is to **not** delete the `if` statement but move it outwards. In that case, we are certainly not changing the default behaviours for other backends.

**Review by shigma — APPROVED** [review]
